import os
from dataclasses import dataclass
from dotenv import load_dotenv

load_dotenv()

# Previous packaged version markers for regression tests: 0078 SCALP EXIT SAFETY | 0089 OPENAI PROMPT QUALITY FIX | 0096 SAFE STOP MARKET RECOVERY | 0234 QUICK BOUNCE RR 1TO2 TPSL FIX | 0237 QUICK BOUNCE REST TICKER FALLBACK | 0238 QUICK BOUNCE SPREAD 0.30

# Previous packaged version marker kept for regression tests: 0078 SCALP EXIT SAFETY
# Previous packaged version marker kept for regression tests: 0092 RUN IMMEDIATE SCAN WAKEUP
# Previous packaged version marker kept for regression tests: 0155 REAL MEXC TPSL TRIGGER FIX
VERSION = "0362 CHATGPT 4H 1H WORKFLOW V27"  # hard-coded; ignore stale Railway BOT_VERSION env

def env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}

def env_float(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except Exception:
        return default

def env_int(name: str, default: int) -> int:
    try:
        return int(float(os.getenv(name, str(default))))
    except Exception:
        return default

@dataclass
class Defaults:
    live_trading: bool = env_bool("LIVE_TRADING", False)
    universe_mode: str = os.getenv("UNIVERSE_MODE", "adaptive")
    scan_market_source: str = os.getenv("SCAN_MARKET_SOURCE", "mexc_binance")
    max_symbols: int = env_int("MAX_SYMBOLS", 100)
    scan_interval_sec: int = env_int("SCAN_INTERVAL_SEC", 5)
    scanner_concurrency: int = env_int("SCANNER_CONCURRENCY", 5)
    scanner_error_slowdown_threshold: int = env_int("SCANNER_ERROR_SLOWDOWN_THRESHOLD", 5)
    scanner_slowdown_max_sec: int = env_int("SCANNER_SLOWDOWN_MAX_SEC", 15)
    ws_update_throttle_ms: int = env_int("WS_UPDATE_THROTTLE_MS", 500)
    ws_max_updates_per_batch: int = env_int("WS_MAX_UPDATES_PER_BATCH", 1000)
    ws_queue_limit: int = env_int("WS_QUEUE_LIMIT", 2000)
    ws_adaptive_slowdown_threshold: int = env_int("WS_ADAPTIVE_SLOWDOWN_THRESHOLD", 1000)
    symbol_refresh_sec: int = env_int("SYMBOL_REFRESH_SEC", 300)
    max_open_positions: int = env_int("MAX_OPEN_POSITIONS", 5)
    risk_pct: float = env_float("RISK_PCT", 0.01)
    strategy_mode: str = os.getenv("STRATEGY_MODE", "hybrid")
    auto_strategy_adaptation: bool = env_bool("AUTO_STRATEGY_ADAPTATION", True)
    regime_adaptation: bool = env_bool("REGIME_ADAPTATION", True)
    mirror_mode: str = os.getenv("MIRROR_MODE", "off")
    spot_confirmation_enabled: bool = env_bool("SPOT_CONFIRMATION_ENABLED", True)
    session_filter_enabled: bool = env_bool("SESSION_FILTER_ENABLED", True)
    america_short_bias_enabled: bool = env_bool("AMERICA_SHORT_BIAS_ENABLED", True)
    max_spread_pct: float = env_float("MAX_SPREAD_PCT", 0.20)
    max_slippage_pct: float = env_float("MAX_SLIPPAGE_PCT", 0.20)
    min_depth_usdt: float = env_float("MIN_DEPTH_USDT", 5000.0)
    max_daily_loss_pct: float = env_float("MAX_DAILY_LOSS_PCT", 3.0)
    max_consecutive_losses: int = env_int("MAX_CONSECUTIVE_LOSSES", 4)
    cooldown_after_close_sec: int = env_int("COOLDOWN_AFTER_CLOSE_SEC", 120)
    limit_timeout_sec: int = env_int("LIMIT_TIMEOUT_SEC", 300)
    proxy_enabled: bool = env_bool("PROXY_ENABLED", False)
    proxy_url: str = os.getenv("PROXY_URL", "")
    mexc_order_leverage: int = env_int("MEXC_ORDER_LEVERAGE", 5)
    mexc_order_open_type: int = env_int("MEXC_ORDER_OPEN_TYPE", 1)
    mexc_recv_window: int = env_int("MEXC_RECV_WINDOW", 20000)
    margin_allocation_enabled: bool = env_bool("MARGIN_ALLOCATION_ENABLED", True)
    require_exchange_protection: bool = env_bool("REQUIRE_EXCHANGE_PROTECTION", True)
    auto_close_on_protection_failed: bool = env_bool("AUTO_CLOSE_ON_PROTECTION_FAILED", True)

    protection_post_open_delay_sec: float = env_float("PROTECTION_POST_OPEN_DELAY_SEC", 1.5)
    protection_position_wait_sec: float = env_float("PROTECTION_POSITION_WAIT_SEC", 6.0)
    protection_position_poll_sec: float = env_float("PROTECTION_POSITION_POLL_SEC", 0.5)
    protection_min_trigger_pct: float = env_float("PROTECTION_MIN_TRIGGER_PCT", 0.12)
    protection_min_trigger_ticks: int = env_int("PROTECTION_MIN_TRIGGER_TICKS", 5)
    protection_distance_expand_mult: float = env_float("PROTECTION_DISTANCE_EXPAND_MULT", 1.25)
    liquidity_retest_default_rr: float = env_float("LIQUIDITY_RETEST_DEFAULT_RR", 3.0)
    liquidity_retest_sl_buffer_pct: float = env_float("LIQUIDITY_RETEST_SL_BUFFER_PCT", 0.04)
    liquidity_retest_time_stop_sec: int = env_int("LIQUIDITY_RETEST_TIME_STOP_SEC", 1800)
    liquidity_retest_min_displacement_pct: float = env_float("LIQUIDITY_RETEST_MIN_DISPLACEMENT_PCT", 0.10)
    liquidity_retest_min_displacement_body: float = env_float("LIQUIDITY_RETEST_MIN_DISPLACEMENT_BODY", 0.55)
    liquidity_retest_min_volume_ratio: float = env_float("LIQUIDITY_RETEST_MIN_VOLUME_RATIO", 1.15)
    liquidity_retest_min_target_rr: float = env_float("LIQUIDITY_RETEST_MIN_TARGET_RR", 1.8)
    liquidity_retest_zone_tolerance_pct: float = env_float("LIQUIDITY_RETEST_ZONE_TOLERANCE_PCT", 0.08)
    liquidity_retest_min_sweep_wick: float = env_float("LIQUIDITY_RETEST_MIN_SWEEP_WICK", 0.25)
    liquidity_retest_min_reclaim_pct: float = env_float("LIQUIDITY_RETEST_MIN_RECLAIM_PCT", 0.04)
    liquidity_retest_max_spread_pct: float = env_float("LIQUIDITY_RETEST_MAX_SPREAD_PCT", 0.18)
    liquidity_retest_min_retest_rejection_wick: float = env_float("LIQUIDITY_RETEST_MIN_RETEST_REJECTION_WICK", 0.25)
    liquidity_retest_min_zone_quality: float = env_float("LIQUIDITY_RETEST_MIN_ZONE_QUALITY", 2.0)
    liquidity_retest_mtf_enabled: bool = env_bool("LIQUIDITY_RETEST_MTF_ENABLED", True)
    liquidity_retest_min_mtf_score: float = env_float("LIQUIDITY_RETEST_MIN_MTF_SCORE", -0.25)
    liquidity_retest_require_clean_path: bool = env_bool("LIQUIDITY_RETEST_REQUIRE_CLEAN_PATH", False)
    liquidity_retest_quality_mode: str = os.getenv("LIQUIDITY_RETEST_QUALITY_MODE", "a_plus")
    scanner_reject_log_enabled: bool = env_bool("SCANNER_REJECT_LOG_ENABLED", True)
    liquidity_runner_enabled: bool = env_bool("LIQUIDITY_RUNNER_ENABLED", False)

    ai_scalping_symbols: str = os.getenv("AI_SCALPING_SYMBOLS", "BTC_USDT,ETH_USDT")
    ai_scalping_min_confidence: float = env_float("AI_SCALPING_MIN_CONFIDENCE", 0.72)
    ai_scalping_ai_entry_filter_enabled: bool = env_bool("AI_SCALPING_AI_ENTRY_FILTER_ENABLED", True)
    ai_scalping_tp_pct: float = env_float("AI_SCALPING_TP_PCT", 0.10)
    ai_scalping_sl_pct: float = env_float("AI_SCALPING_SL_PCT", 0.22)
    ai_scalping_btc_tp_pct: float = env_float("AI_SCALPING_BTC_TP_PCT", 0.09)
    ai_scalping_btc_sl_pct: float = env_float("AI_SCALPING_BTC_SL_PCT", 0.18)
    ai_scalping_eth_tp_pct: float = env_float("AI_SCALPING_ETH_TP_PCT", 0.12)
    ai_scalping_eth_sl_pct: float = env_float("AI_SCALPING_ETH_SL_PCT", 0.24)
    ai_scalping_btc_min_tp_pct: float = env_float("AI_SCALPING_BTC_MIN_TP_PCT", 0.08)
    ai_scalping_btc_max_tp_pct: float = env_float("AI_SCALPING_BTC_MAX_TP_PCT", 0.12)
    ai_scalping_eth_min_tp_pct: float = env_float("AI_SCALPING_ETH_MIN_TP_PCT", 0.10)
    ai_scalping_eth_max_tp_pct: float = env_float("AI_SCALPING_ETH_MAX_TP_PCT", 0.16)
    ai_scalping_sl_tp_multiplier: float = env_float("AI_SCALPING_SL_TP_MULTIPLIER", 2.0)
    ai_scalping_max_spread_pct: float = env_float("AI_SCALPING_MAX_SPREAD_PCT", 0.08)
    ai_scalping_spot_imbalance_ratio: float = env_float("AI_SCALPING_SPOT_IMBALANCE_RATIO", 1.35)
    ai_scalping_btc_spot_imbalance_ratio: float = env_float("AI_SCALPING_BTC_SPOT_IMBALANCE_RATIO", 1.35)
    ai_scalping_eth_spot_imbalance_ratio: float = env_float("AI_SCALPING_ETH_SPOT_IMBALANCE_RATIO", 1.30)
    ai_scalping_futures_momentum_min_pct: float = env_float("AI_SCALPING_FUTURES_MOMENTUM_MIN_PCT", 0.015)
    ai_scalping_futures_max_against_pct: float = env_float("AI_SCALPING_FUTURES_MAX_AGAINST_PCT", 0.035)
    ai_scalping_quality_filters_enabled: bool = env_bool("AI_SCALPING_QUALITY_FILTERS_ENABLED", False)
    ai_scalping_quality_min_confidence: float = env_float("AI_SCALPING_QUALITY_MIN_CONFIDENCE", 0.72)
    ai_scalping_quality_cooldown_sec: int = env_int("AI_SCALPING_QUALITY_COOLDOWN_SEC", 45)
    ai_scalping_quality_min_atr_pct: float = env_float("AI_SCALPING_QUALITY_MIN_ATR_PCT", 0.035)
    ai_scalping_quality_min_ema_gap_pct: float = env_float("AI_SCALPING_QUALITY_MIN_EMA_GAP_PCT", 0.015)
    ai_scalping_quality_min_ret_5m_abs_pct: float = env_float("AI_SCALPING_QUALITY_MIN_RET_5M_ABS_PCT", 0.035)
    ai_scalping_setup_min_quality_score: float = env_float("AI_SCALPING_SETUP_MIN_QUALITY_SCORE", 42.0)
    ai_scalping_ai_cooldown_sec: int = env_int("AI_SCALPING_AI_COOLDOWN_SEC", 8)
    ai_scalping_openai_fallback_enabled: bool = env_bool("AI_SCALPING_OPENAI_FALLBACK_ENABLED", False)
    ai_scalping_json_mode_enabled: bool = env_bool("AI_SCALPING_JSON_MODE_ENABLED", True)
    ai_scalping_liquidation_stop_mode: bool = env_bool("AI_SCALPING_LIQUIDATION_STOP_MODE", False)
    ai_scalping_liq_margin_pct: float = env_float("AI_SCALPING_LIQ_MARGIN_PCT", 0.01)
    ai_scalping_liq_buffer_pct: float = env_float("AI_SCALPING_LIQ_BUFFER_PCT", 0.00)
    ai_scalping_liq_max_leverage: int = env_int("AI_SCALPING_LIQ_MAX_LEVERAGE", 200)
    ai_scalping_protection_delay_sec: float = env_float("AI_SCALPING_PROTECTION_DELAY_SEC", 3.0)
    trade_margin_pct: float = env_float("TRADE_MARGIN_PCT", 0.10)

    quick_bounce_enabled: bool = env_bool("QUICK_BOUNCE_ENABLED", False)
    quick_bounce_top_coins: int = env_int("QUICK_BOUNCE_TOP_COINS", 200)
    quick_bounce_scan_interval_sec: int = env_int("QUICK_BOUNCE_SCAN_INTERVAL_SEC", 900)
    quick_bounce_trade_margin_pct: float = env_float("QUICK_BOUNCE_TRADE_MARGIN_PCT", 0.10)
    quick_bounce_max_open_positions: int = env_int("QUICK_BOUNCE_MAX_OPEN_POSITIONS", 5)
    quick_bounce_leverage: int = env_int("QUICK_BOUNCE_LEVERAGE", 10)
    quick_bounce_tp_pct: float = env_float("QUICK_BOUNCE_TP_PCT", 2.5)
    quick_bounce_sl_pct: float = env_float("QUICK_BOUNCE_SL_PCT", 1.5)
    quick_bounce_rr: float = env_float("QUICK_BOUNCE_RR", 1.6667)
    quick_bounce_time_stop_sec: int = env_int("QUICK_BOUNCE_TIME_STOP_SEC", 43200)
    quick_bounce_drop_4h_pct: float = env_float("QUICK_BOUNCE_DROP_4H_PCT", 5.0)
    quick_bounce_pump_4h_pct: float = env_float("QUICK_BOUNCE_PUMP_4H_PCT", 5.0)
    quick_bounce_reversal_pct: float = env_float("QUICK_BOUNCE_REVERSAL_PCT", 1.0)
    quick_bounce_min_volume_ratio: float = env_float("QUICK_BOUNCE_MIN_VOLUME_RATIO", 1.15)
    quick_bounce_max_spread_pct: float = env_float("QUICK_BOUNCE_MAX_SPREAD_PCT", 0.30)
    quick_bounce_min_24h_volume_usdt: float = env_float("QUICK_BOUNCE_MIN_24H_VOLUME_USDT", 20000000.0)
    quick_bounce_btc_filter_enabled: bool = env_bool("QUICK_BOUNCE_BTC_FILTER_ENABLED", True)
    quick_bounce_btc_max_drop_1h_pct: float = env_float("QUICK_BOUNCE_BTC_MAX_DROP_1H_PCT", 2.0)
    quick_bounce_btc_max_pump_1h_pct: float = env_float("QUICK_BOUNCE_BTC_MAX_PUMP_1H_PCT", 2.0)
    quick_bounce_cooldown_after_close_sec: int = env_int("QUICK_BOUNCE_COOLDOWN_AFTER_CLOSE_SEC", 21600)
    quick_bounce_max_daily_loss_pct: float = env_float("QUICK_BOUNCE_MAX_DAILY_LOSS_PCT", 5.0)
    quick_bounce_anomaly_timeframe: str = os.getenv("QUICK_BOUNCE_ANOMALY_TIMEFRAME", "1h")
    quick_bounce_confirm_timeframe: str = os.getenv("QUICK_BOUNCE_CONFIRM_TIMEFRAME", "15m")
    quick_bounce_max_candidates: int = env_int("QUICK_BOUNCE_MAX_CANDIDATES", 5)

    impulse_dump_enabled: bool = env_bool("IMPULSE_DUMP_ENABLED", False)
    impulse_dump_top_coins: int = env_int("IMPULSE_DUMP_TOP_COINS", 200)
    impulse_dump_scan_interval_sec: int = env_int("IMPULSE_DUMP_SCAN_INTERVAL_SEC", 900)
    impulse_dump_trade_margin_pct: float = env_float("IMPULSE_DUMP_TRADE_MARGIN_PCT", 0.10)
    impulse_dump_max_open_positions: int = env_int("IMPULSE_DUMP_MAX_OPEN_POSITIONS", 5)
    impulse_dump_leverage: int = env_int("IMPULSE_DUMP_LEVERAGE", 10)
    impulse_dump_sl_pct: float = env_float("IMPULSE_DUMP_SL_PCT", 2.0)
    impulse_dump_total_drop_target_pct: float = env_float("IMPULSE_DUMP_TOTAL_DROP_TARGET_PCT", 10.0)
    impulse_dump_min_drop_pct: float = env_float("IMPULSE_DUMP_MIN_DROP_PCT", 3.0)
    impulse_dump_max_drop_pct: float = env_float("IMPULSE_DUMP_MAX_DROP_PCT", 6.0)
    impulse_dump_15m_min_drop_pct: float = env_float("IMPULSE_DUMP_15M_MIN_DROP_PCT", 0.1)
    impulse_dump_15m_max_drop_pct: float = env_float("IMPULSE_DUMP_15M_MAX_DROP_PCT", 6.0)
    impulse_dump_4h_max_drop_pct: float = env_float("IMPULSE_DUMP_4H_MAX_DROP_PCT", 6.0)
    impulse_dump_24h_max_drop_pct: float = env_float("IMPULSE_DUMP_24H_MAX_DROP_PCT", 6.0)
    impulse_dump_time_stop_sec: int = env_int("IMPULSE_DUMP_TIME_STOP_SEC", 86400)
    impulse_dump_min_volume_ratio: float = env_float("IMPULSE_DUMP_MIN_VOLUME_RATIO", 1.05)
    impulse_dump_max_spread_pct: float = env_float("IMPULSE_DUMP_MAX_SPREAD_PCT", 0.30)
    impulse_dump_min_24h_volume_usdt: float = env_float("IMPULSE_DUMP_MIN_24H_VOLUME_USDT", 20000000.0)
    impulse_dump_btc_filter_enabled: bool = env_bool("IMPULSE_DUMP_BTC_FILTER_ENABLED", True)
    impulse_dump_btc_max_pump_1h_pct: float = env_float("IMPULSE_DUMP_BTC_MAX_PUMP_1H_PCT", 1.5)
    impulse_dump_cooldown_after_close_sec: int = env_int("IMPULSE_DUMP_COOLDOWN_AFTER_CLOSE_SEC", 0)
    impulse_dump_max_daily_loss_pct: float = env_float("IMPULSE_DUMP_MAX_DAILY_LOSS_PCT", 5.0)
    impulse_dump_stop_after_consecutive_sl: int = env_int("IMPULSE_DUMP_STOP_AFTER_CONSECUTIVE_SL", 3)
    impulse_dump_anomaly_timeframe: str = os.getenv("IMPULSE_DUMP_ANOMALY_TIMEFRAME", "1h")
    impulse_dump_confirm_timeframe: str = os.getenv("IMPULSE_DUMP_CONFIRM_TIMEFRAME", "15m")
    impulse_dump_max_candidates: int = env_int("IMPULSE_DUMP_MAX_CANDIDATES", 5)
    impulse_dump_manage_only_tpsl: bool = env_bool("IMPULSE_DUMP_MANAGE_ONLY_TPSL", True)


    orderflow_impulse_enabled: bool = env_bool("ORDERFLOW_IMPULSE_ENABLED", False)
    orderflow_impulse_top_coins: int = env_int("ORDERFLOW_IMPULSE_TOP_COINS", 100)
    orderflow_impulse_scan_interval_sec: int = env_int("ORDERFLOW_IMPULSE_SCAN_INTERVAL_SEC", 60)
    orderflow_impulse_trade_margin_pct: float = env_float("ORDERFLOW_IMPULSE_TRADE_MARGIN_PCT", 0.10)
    orderflow_impulse_max_open_positions: int = env_int("ORDERFLOW_IMPULSE_MAX_OPEN_POSITIONS", 3)
    orderflow_impulse_leverage: int = env_int("ORDERFLOW_IMPULSE_LEVERAGE", 10)
    orderflow_impulse_tp_pct: float = env_float("ORDERFLOW_IMPULSE_TP_PCT", 2.0)
    orderflow_impulse_sl_pct: float = env_float("ORDERFLOW_IMPULSE_SL_PCT", 3.0)
    orderflow_impulse_time_stop_sec: int = env_int("ORDERFLOW_IMPULSE_TIME_STOP_SEC", 86400)
    orderflow_impulse_min_volume_ratio: float = env_float("ORDERFLOW_IMPULSE_MIN_VOLUME_RATIO", 1.5)
    orderflow_impulse_min_trend_pct: float = env_float("ORDERFLOW_IMPULSE_MIN_TREND_PCT", 0.25)
    orderflow_impulse_min_imbalance_abs: float = env_float("ORDERFLOW_IMPULSE_MIN_IMBALANCE_ABS", 0.08)
    orderflow_impulse_max_spread_pct: float = env_float("ORDERFLOW_IMPULSE_MAX_SPREAD_PCT", 0.20)
    orderflow_impulse_min_24h_volume_usdt: float = env_float("ORDERFLOW_IMPULSE_MIN_24H_VOLUME_USDT", 5000000.0)
    orderflow_impulse_manage_only_tpsl: bool = env_bool("ORDERFLOW_IMPULSE_MANAGE_ONLY_TPSL", True)


    cascade_hunter_enabled: bool = env_bool("CASCADE_HUNTER_ENABLED", False)
    cascade_hunter_top_coins: int = env_int("CASCADE_HUNTER_TOP_COINS", 100)
    cascade_hunter_scan_interval_sec: int = env_int("CASCADE_HUNTER_SCAN_INTERVAL_SEC", 60)
    cascade_hunter_trade_margin_pct: float = env_float("CASCADE_HUNTER_TRADE_MARGIN_PCT", 0.10)
    cascade_hunter_max_open_positions: int = env_int("CASCADE_HUNTER_MAX_OPEN_POSITIONS", 3)
    cascade_hunter_leverage: int = env_int("CASCADE_HUNTER_LEVERAGE", 10)
    cascade_hunter_tp_pct: float = env_float("CASCADE_HUNTER_TP_PCT", 4.0)
    cascade_hunter_sl_pct: float = env_float("CASCADE_HUNTER_SL_PCT", 2.0)
    cascade_hunter_time_stop_sec: int = env_int("CASCADE_HUNTER_TIME_STOP_SEC", 14400)
    cascade_hunter_min_liq_usd_1m: float = env_float("CASCADE_HUNTER_MIN_LIQ_USD_1M", 30000.0)  # legacy/stat only after v0277
    cascade_hunter_min_pressure_ratio: float = env_float("CASCADE_HUNTER_MIN_PRESSURE_RATIO", 0.070)
    cascade_hunter_min_volume_ratio: float = env_float("CASCADE_HUNTER_MIN_VOLUME_RATIO", 2.2)
    cascade_hunter_min_price_move_pct: float = env_float("CASCADE_HUNTER_MIN_PRICE_MOVE_PCT", 0.45)
    cascade_hunter_max_spread_pct: float = env_float("CASCADE_HUNTER_MAX_SPREAD_PCT", 0.12)
    cascade_hunter_min_24h_volume_usdt: float = env_float("CASCADE_HUNTER_MIN_24H_VOLUME_USDT", 5000000.0)
    cascade_hunter_max_price_move_pct: float = env_float("CASCADE_HUNTER_MAX_PRICE_MOVE_PCT", 1.80)
    cascade_hunter_min_delta_ratio_abs: float = env_float("CASCADE_HUNTER_MIN_DELTA_RATIO_ABS", 0.20)
    cascade_hunter_min_score: float = env_float("CASCADE_HUNTER_MIN_SCORE", 86.0)
    cascade_hunter_tp1_r: float = env_float("CASCADE_HUNTER_TP1_R", 1.0)
    cascade_hunter_tp2_r: float = env_float("CASCADE_HUNTER_TP2_R", 2.0)
    cascade_hunter_tp1_fraction: float = env_float("CASCADE_HUNTER_TP1_FRACTION", 0.50)


    strongest_coin_enabled: bool = env_bool("STRONGEST_COIN_ENABLED", False)
    strongest_coin_top_coins: int = env_int("STRONGEST_COIN_TOP_COINS", 200)
    strongest_coin_scan_interval_sec: int = env_int("STRONGEST_COIN_SCAN_INTERVAL_SEC", 60)
    strongest_coin_trade_margin_pct: float = env_float("STRONGEST_COIN_TRADE_MARGIN_PCT", 0.10)
    strongest_coin_max_open_positions: int = env_int("STRONGEST_COIN_MAX_OPEN_POSITIONS", 1)
    strongest_coin_leverage: int = env_int("STRONGEST_COIN_LEVERAGE", 10)
    strongest_coin_min_24h_volume_usdt: float = env_float("STRONGEST_COIN_MIN_24H_VOLUME_USDT", 5000000.0)
    strongest_coin_max_spread_pct: float = env_float("STRONGEST_COIN_MAX_SPREAD_PCT", 0.15)
    strongest_coin_min_strength_score: float = env_float("STRONGEST_COIN_MIN_STRENGTH_SCORE", 0.60)
    strongest_coin_min_rs_btc_15m_pct: float = env_float("STRONGEST_COIN_MIN_RS_BTC_15M_PCT", 0.50)
    strongest_coin_btc_panic_5m_pct: float = env_float("STRONGEST_COIN_BTC_PANIC_5M_PCT", -1.50)
    strongest_coin_min_pullback_pct: float = env_float("STRONGEST_COIN_MIN_PULLBACK_PCT", 0.35)
    strongest_coin_max_pullback_pct: float = env_float("STRONGEST_COIN_MAX_PULLBACK_PCT", 1.80)
    strongest_coin_max_pullback_depth: float = env_float("STRONGEST_COIN_MAX_PULLBACK_DEPTH", 0.45)
    strongest_coin_min_hold_recovery_pct: float = env_float("STRONGEST_COIN_MIN_HOLD_RECOVERY_PCT", 0.30)
    strongest_coin_stop_buffer_pct: float = env_float("STRONGEST_COIN_STOP_BUFFER_PCT", 0.35)
    strongest_coin_min_sl_pct: float = env_float("STRONGEST_COIN_MIN_SL_PCT", 1.60)
    strongest_coin_max_sl_pct: float = env_float("STRONGEST_COIN_MAX_SL_PCT", 2.80)
    strongest_coin_tp1_r: float = env_float("STRONGEST_COIN_TP1_R", 1.0)
    strongest_coin_tp2_r: float = env_float("STRONGEST_COIN_TP2_R", 2.0)
    strongest_coin_tp1_fraction: float = env_float("STRONGEST_COIN_TP1_FRACTION", 0.50)
    strongest_coin_time_stop_sec: int = env_int("STRONGEST_COIN_TIME_STOP_SEC", 600)
    strongest_coin_cooldown_after_close_sec: int = env_int("STRONGEST_COIN_COOLDOWN_AFTER_CLOSE_SEC", 3600)

    knife_reversal_enabled: bool = env_bool("KNIFE_REVERSAL_ENABLED", False)
    knife_reversal_top_coins: int = env_int("KNIFE_REVERSAL_TOP_COINS", 100)
    knife_reversal_scan_interval_sec: int = env_int("KNIFE_REVERSAL_SCAN_INTERVAL_SEC", 60)
    knife_reversal_trade_margin_pct: float = env_float("KNIFE_REVERSAL_TRADE_MARGIN_PCT", 0.10)
    knife_reversal_max_open_positions: int = env_int("KNIFE_REVERSAL_MAX_OPEN_POSITIONS", 3)
    knife_reversal_leverage: int = env_int("KNIFE_REVERSAL_LEVERAGE", 10)
    knife_reversal_tp_pct: float = env_float("KNIFE_REVERSAL_TP_PCT", 5.0)
    knife_reversal_wick_sl_buffer_pct: float = env_float("KNIFE_REVERSAL_WICK_SL_BUFFER_PCT", 0.20)
    knife_reversal_min_24h_volume_usdt: float = env_float("KNIFE_REVERSAL_MIN_24H_VOLUME_USDT", 5000000.0)
    knife_reversal_min_wick_pct: float = env_float("KNIFE_REVERSAL_MIN_WICK_PCT", 1.20)
    knife_reversal_min_reclaim_pct: float = env_float("KNIFE_REVERSAL_MIN_RECLAIM_PCT", 50.0)
    knife_reversal_min_volume_ratio: float = env_float("KNIFE_REVERSAL_MIN_VOLUME_RATIO", 2.0)
    knife_reversal_min_delta_ratio: float = env_float("KNIFE_REVERSAL_MIN_DELTA_RATIO", 0.05)
    knife_reversal_min_imbalance: float = env_float("KNIFE_REVERSAL_MIN_IMBALANCE", 0.08)
    knife_reversal_max_spread_pct: float = env_float("KNIFE_REVERSAL_MAX_SPREAD_PCT", 0.25)
    knife_reversal_time_stop_sec: int = env_int("KNIFE_REVERSAL_TIME_STOP_SEC", 86400)

    multi_strategy_enabled: bool = env_bool("MULTI_STRATEGY_ENABLED", False)
    multi_strategy_top_coins: int = env_int("MULTI_STRATEGY_TOP_COINS", 100)
    multi_strategy_scan_interval_sec: int = env_int("MULTI_STRATEGY_SCAN_INTERVAL_SEC", 60)
    multi_strategy_max_open_positions: int = env_int("MULTI_STRATEGY_MAX_OPEN_POSITIONS", 3)

    # v0175 Boost Whitelist Commands: /boost_list accepts BTC,ETH,SOL format and /boost_list_del clears trusted zero-fee symbols.
    boost_zero_fee_scanner_enabled: bool = env_bool("BOOST_ZERO_FEE_SCANNER_ENABLED", True)
    boost_balance_share: float = env_float("BOOST_BALANCE_SHARE", 0.10)
    boost_target_multiplier: float = env_float("BOOST_TARGET_MULTIPLIER", 20.0)
    boost_session_hours: float = env_float("BOOST_SESSION_HOURS", 6.0)
    boost_max_session_loss_pct: float = env_float("BOOST_MAX_SESSION_LOSS_PCT", 18.0)
    boost_max_consecutive_losses: int = env_int("BOOST_MAX_CONSECUTIVE_LOSSES", 1)
    boost_auto_leverage: bool = env_bool("BOOST_AUTO_LEVERAGE", True)
    boost_min_leverage: int = env_int("BOOST_MIN_LEVERAGE", 30)
    boost_max_leverage: int = env_int("BOOST_MAX_LEVERAGE", 50)
    boost_use_full_bank_per_trade: bool = env_bool("BOOST_USE_FULL_BANK_PER_TRADE", False)
    boost_risk_pct_per_trade: float = env_float("BOOST_RISK_PCT_PER_TRADE", 0.035)
    boost_auto_rotate_symbols: bool = env_bool("BOOST_AUTO_ROTATE_SYMBOLS", True)
    boost_stop_when_target_reached: bool = env_bool("BOOST_STOP_WHEN_TARGET_REACHED", True)
    boost_max_symbols_scan: int = env_int("BOOST_MAX_SYMBOLS_SCAN", 300)
    boost_min_quote_volume_usdt: float = env_float("BOOST_MIN_QUOTE_VOLUME_USDT", 2500000.0)
    boost_min_atr_pct: float = env_float("BOOST_MIN_ATR_PCT", 0.06)
    boost_max_spread_pct: float = env_float("BOOST_MAX_SPREAD_PCT", 0.045)
    boost_spot_imbalance_ratio: float = env_float("BOOST_SPOT_IMBALANCE_RATIO", 1.45)
    boost_futures_momentum_min_pct: float = env_float("BOOST_FUTURES_MOMENTUM_MIN_PCT", 0.09)
    boost_futures_max_against_pct: float = env_float("BOOST_FUTURES_MAX_AGAINST_PCT", 0.02)
    boost_min_tp_pct: float = env_float("BOOST_MIN_TP_PCT", 0.16)
    boost_max_tp_pct: float = env_float("BOOST_MAX_TP_PCT", 0.48)
    boost_sl_tp_multiplier: float = env_float("BOOST_SL_TP_MULTIPLIER", 2.40)
    boost_scan_interval_sec: int = env_int("BOOST_SCAN_INTERVAL_SEC", 1)
    boost_allow_fee_fallback: bool = env_bool("BOOST_ALLOW_FEE_FALLBACK", True)
    boost_zero_fee_symbols: str = os.getenv("BOOST_ZERO_FEE_SYMBOLS", "AAPLUSDT,AAVEUSDT,ADAUSDT,AMDUSDT,ANTHROPICUSDT,APEUSDT,ARMUSDT,ASTERUSDT,ASTSUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BEUSDT,BILLUSDT,BLESSUSDT,BNBUSDT,BRETTUSDT,BTCUSDT,BULLAUSDT,BUSDT,CBRSUSDT,CHIPUSDT,COAIUSDT,XCU_USDT,CVNAUSDT,DOGEUSDT,DOTUSDT,ENJUSDT,ETHFIUSDT,ETHUSDT,FLOKIUSDT,FLNCUSDT,FOLKSUSDT,FUTUUSDT,GALAUSDT,GASNGUSDT,GIGGLEUSDT,GOATUSDT,PAXG_USDT,XAUT_USDT,GOOGLUSDT,GRTUSDT,HBARUSDT,HYPEUSDT,IBMUSDT,ICPUSDT,INJUSDT,INTCUSDT,INTUUSDT,IONQUSDT,JASMYUSDT,JUPUSDT,LABUSDT,LAYERUSDT,LIGHTUSDT,LINKUSDT,LTCUSDT,LYNUSDT,MEGAUSDT,MSTRUSDT,MUUSDT,MUUUSDT,MYXUSDT,NAS100_USDT,NBISUSDT,NEARUSDT,XNI_USDT,NVDAUSDT,BRENT_USDT,WTI_USDT,ONDOUSDT,OPUSDT,ORDIUSDT,XPD_USDT,PENGUINUSDT,PENGUUSDT,PEPEUSDT,PIPPINUSDT,PIXELUSDT,XPT_USDT,PNUTUSDT,POLUSDT,POWERUSDT,PUMPUSDT,PYTHUSDT,QCOMUSDT,QQQUSDT,RENDERUSDT,RIVERUSDT,RKLBUSDT,SAMSUNGUSDT,SEIUSDT,SHIBUSDT,XAG_USDT,SKHYNIXUSDT,SKYAIUSDT,SNDKUSDT,SOLUSDT,SP500_USDT,SPACEXUSDT,SPCXUSDT,SPOTUSDT,STOUSDT,STRKUSDT,STXSTOCKUSDT,SUIUSDT,TAOUSDT,TONUSDT,TRUMPUSDT,TSLAUSDT,UNIUSDT,US30_USDT,VIRTUALUSDT,VVVUSDT,WDCUSDT,WIFUSDT,WLDUSDT,WLFIUSDT,XAIUSDT,XLMUSDT,XMRUSDT,XOMUSDT,XPLUSDT,XRPUSDT,ZECUSDT,ZROUSDT")

    boost_blocked_symbols_json: str = os.getenv("BOOST_BLOCKED_SYMBOLS_JSON", "{}")
    # v0181: BOOST live uses the same clean entry -> MEXC native TP/SL -> local fast monitor flow as BTC/ETH scalping.
    # Missing/late TP/SL confirmation must not instantly close a live BOOST position.
    boost_live_safe_execution: bool = env_bool("BOOST_LIVE_SAFE_EXECUTION", True)
    boost_manage_only_tpsl: bool = env_bool("BOOST_MANAGE_ONLY_TPSL", True)
    boost_live_panel_enabled: bool = env_bool("BOOST_LIVE_PANEL_ENABLED", True)
    boost_live_panel_interval_sec: int = env_int("BOOST_LIVE_PANEL_INTERVAL_SEC", 2)
    boost_parallel_scan_enabled: bool = env_bool("BOOST_PARALLEL_SCAN_ENABLED", True)
    boost_rotate_only_if_profit: bool = env_bool("BOOST_ROTATE_ONLY_IF_PROFIT", True)
    boost_min_profit_to_rotate_pct: float = env_float("BOOST_MIN_PROFIT_TO_ROTATE_PCT", 0.04)
    boost_rotate_strength_multiplier: float = env_float("BOOST_ROTATE_STRENGTH_MULTIPLIER", 1.35)
    boost_rotate_min_score_gap: float = env_float("BOOST_ROTATE_MIN_SCORE_GAP", 5.0)
    boost_rotate_cooldown_sec: int = env_int("BOOST_ROTATE_COOLDOWN_SEC", 1)
    boost_rescue_rotation_enabled: bool = env_bool("BOOST_RESCUE_ROTATION_ENABLED", False)
    boost_rescue_min_score_multiplier: float = env_float("BOOST_RESCUE_MIN_SCORE_MULTIPLIER", 1.70)
    boost_rescue_min_score_gap: float = env_float("BOOST_RESCUE_MIN_SCORE_GAP", 18.0)
    boost_rescue_expected_move_loss_mult: float = env_float("BOOST_RESCUE_EXPECTED_MOVE_LOSS_MULT", 2.50)
    boost_rescue_max_loss_pct: float = env_float("BOOST_RESCUE_MAX_LOSS_PCT", 0.70)
    boost_rescue_cooldown_sec: int = env_int("BOOST_RESCUE_COOLDOWN_SEC", 180)
    boost_rescue_max_per_hour: int = env_int("BOOST_RESCUE_MAX_PER_HOUR", 2)

DEFAULTS = Defaults()
DB_PATH = os.getenv("DATABASE_PATH", "bot_data.sqlite3")
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "")
ADMIN_IDS = os.getenv("ADMIN_IDS", "")
DEFAULT_EXCHANGE = os.getenv("DEFAULT_EXCHANGE", "mexc").lower()
